version: '3.8'

services:
  web:
    build: .
    container_name: ChronoTube
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - PROJECT_SECRET_KEY=${PROJECT_SECRET_KEY}
      - ENV_DEVELOPMENT=${ENV_DEVELOPMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - YOUTUBE_API_KEYS=${YOUTUBE_API_KEYS}
      - DEFAULT_QUERY=${DEFAULT_QUERY}

  celery:
    build: .
    container_name: CeleryWorker
    command: celery -A ChronoTube worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    container_name: CeleryBeat
    command: celery -A ChronoTube beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine
    container_name: my_redis
    ports:
      - "6370:6379"

  db:
    image: mysql:5.7
    container_name: my_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
