# Generated by Django 5.0.6 on 2024-10-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("publishedAt", models.DateTimeField()),
                ("thumbnail_url", models.URLField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["publishedAt"], name="core_video_publish_fb2b12_idx"
                    )
                ],
            },
        ),
    ]
