# Generated by Django 5.0.6 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "video_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("publishedAt", models.DateTimeField()),
                ("thumbnail_url", models.URLField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["publishedAt"], name="cronApp_vid_publish_09a9c7_idx"
                    )
                ],
            },
        ),
    ]
