# Generated by Django 5.0.6 on 2024-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "video_id",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                ("publishedAt", models.DateTimeField()),
                ("thumbnail_url", models.URLField(null=True)),
                ("addedAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["title"], name="cronApp_vid_title_feabe1_idx"),
                    models.Index(
                        fields=["description"], name="cronApp_vid_descrip_6943ba_idx"
                    ),
                    models.Index(
                        fields=["publishedAt"], name="cronApp_vid_publish_09a9c7_idx"
                    ),
                ],
            },
        ),
    ]
